apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-argocd-website.fullname" . }}
  labels:
    {{- include "helm-argocd-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "helm-argocd-website.selectorLabels" . | nindent 4 }}
